//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement_Info
    {
        public int Member_id { get; set; }
        public int Committee_Member_id { get; set; }
        public int Announcement_id { get; set; }
    
        public virtual Announcement Announcement { get; set; }
        public virtual Committee_Members Committee_Members { get; set; }
        public virtual Member Member { get; set; }
    }
}
