//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting_Arrangements
    {
        public int Project_id { get; set; }
        public int Committee_Member_id { get; set; }
        public int Meeting_id { get; set; }
    
        public virtual Committee_Members Committee_Members { get; set; }
        public virtual Meeting Meeting { get; set; }
        public virtual Project Project { get; set; }
    }
}
